# These are supported funding model platforms

github: ['Art-Spaces', 'thisismydesign']
patreon: ELEC ART SPACE.
open_collective: ELEC ART SPACE.
ko_fi: ELEC ART SPACE.
community_bridge: ELEC ART SPACE.
liberapay: ELEC ART SPACE.
issuehunt: ELEC ART SPACE.
otechie: ELEC ART SPACE.
custom: ['BTC-ADDR：bc1qv3yuhsqhs2wjstjqj6va3z84pvrar8jkme3der', 'ETH-ADDR：0x4CA3002dfA8145d7C57486e61581A363680F277c', 'XMR-ADDR：4AjwE2amUShWWe7Y5NbVbHcCaRVbftubyaMgy69MRjSWMyGa5XUgnfaS7Bncu1Et3RCLASN1k4vG1a5raoJS4uhqMdPXXoe']