# Basic Configuration
encoding: UTF-8
locale: en-US
title: "ANON SYS, INC."
keyword: "ANON SYS, INC."
email: 0XE7BC5E3W@onion.org
organization: "ANON SYS, INC."
description: >- # this means to ignore newlines until "baseurl:"
  WE ARE ANON SYS. WE ARE LEGION.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/resource/icon/favicon/icon-32x32.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed

##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##

#  ────────────────────────(START AUTOMATED BUILD SERVICE)─────────────────────────────────

# PaaS Containers VMS-0XPTO Configuration
remote_network_vm_for_anon_inc_title: ANON SYS, INC.
remote_network_vm_for_anon_inc_description: WE ARE ANON SYS. WE ARE LEGION.
remote_network_vm_for_anon_inc_favicon: "/OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/icon/favicon/icon-32x32.png"
remote_network_vm_for_anon_inc_base_network: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC
remote_network_vm_for_anon_inc_base_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/
remote_network_vm_for_anon_inc_base_static_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/

remote_network_anon_token_verify: "Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQCVqEWxkJBW8NzRAPBqy3KXlI9ibS1ib5XsMfq3GPakox5ZIxuhCLwR9yKibaLibicGZYViaSewHicvOMc43EBhtRnFloW"
remote_network_anon_token_api: "6xykWLEnztKmnF5VgzTQibOvqoFFfJ8cOyOiaDTO6qPDDRFByohic71lqicZqXu0paicZRpjRmqYL2bPlVlPKT9jAyxq1mqQbXz8Mr4t1J3nvnX11VdcWeUHqFI6lzs3rXv0n"
remote_network_vm_for_products_projects_anon_okrs_dark_models_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/products/projects/anon_okrs/anon_okrs_dark_models_v5.webp
remote_network_vm_for_products_projects_anon_okrs_light_models_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/products/projects/anon_okrs/anon_okrs_light_models_v5.webp

# PaaS Containers VMS-0XPTO i18n All Configuration

# PaaS Containers VMS-0XPTO i18n Translate API Configuration
remote_network_translate_api:
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/USA.svg
  code_name: USA
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/CHN
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/CHN.svg
  code_name: CHN
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/DEU
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/DEU.svg
  code_name: DEU
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/ESP
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/ESP.svg
  code_name: ESP
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/HKG
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/HKG.svg
  code_name: HKG
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/JPN
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/JPN.svg
  code_name: JPN
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/KOR
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/KOR.svg
  code_name: KOR
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/KSA
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/KSA.svg
  code_name: KSA
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/RUS
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/RUS.svg
  code_name: RUS
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/intl/UK
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/UK.svg
  code_name: UK


# PaaS Containers VMS-0XPTO i18n Singleton Model - Anon OKR - Translate API Configuration
remote_network_anon_okr_translate_api:
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/USA
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/USA.svg
  code_name: USA
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/CHN
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/CHN.svg
  code_name: CHN
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/DEU
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/DEU.svg
  code_name: DEU
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/ESP
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/ESP.svg
  code_name: ESP
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/HKG
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/HKG.svg
  code_name: HKG
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/JPN
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/JPN.svg
  code_name: JPN
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/KOR
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/KOR.svg
  code_name: KOR
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/KSA
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/KSA.svg
  code_name: KSA
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/RUS
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/RUS.svg
  code_name: RUS
-
  code_id: translate-api
  code_link: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-G0ZF7/RemotelyNetwork/Actions=InvokeRequest/TokenKeyPairs=Authorization/PrivatizedAPIs/Services/BizProducts/ANON-OKRs-E/Intl/USA
  code_icon: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/i18n/UK.svg
  code_name: UK


# PaaS Containers VMS-0XPTO i18n Menu API
main_router_i18n_USA:
- # Level 1 Menu => None Subset
  router_api_id: home
  label_api: Home
  link_api: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC
  role_api: #
- # Level 2 Menu => Subset (1 -> 1.1 ~ 1.2) & Subset (2 -> 2.1 ~ 2.2) & Subset (3 -> 3.1 ~ 3.2)
  router_api_id: activity
  label_api: Activity
  link_api: #
  role_api: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
  level_menu_1:
      level_menu_label: X Live
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_1_1:
          level_menu_label: Live Event
          level_menu_link: javascript:void(0);
      level_menu_1_2:
          level_menu_label: Live Stream
          level_menu_link: javascript:void(0);
      level_menu_1_3:
          level_menu_label: Live Meetings
          level_menu_link: javascript:void(0);
  level_menu_2:
      level_menu_label: X News
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_2_1:
          level_menu_label: Media Flow
          level_menu_link: javascript:void(0);
      level_menu_2_2:
          level_menu_label: Data Report
          level_menu_link: javascript:void(0);
      level_menu_2_3:
          level_menu_label: Breaking News
          level_menu_link: javascript:void(0);
  level_menu_3:
      level_menu_label: X Plans
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_3_1:
          level_menu_label: Action
          level_menu_link: javascript:void(0);
      level_menu_3_2:
          level_menu_label: Recruit
          level_menu_link: javascript:void(0);
      level_menu_3_3:
          level_menu_label: Public Welfare
          level_menu_link: javascript:void(0);
- # Level 3 Menu => Subset (1 -> 1.1 ~ 1.2) & Subset (2 -> 2.1 ~ 2.2) & Subset (3 -> 3.1 ~ 3.2)
  router_api_id: explore
  label_api: Explore
  link_api: #
  role_api: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
  level_menu_1:
      level_menu_label: Labs
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_1_1:
          level_menu_label: SIS-UJFXJTNT
          level_menu_link: javascript:void(0);
      level_menu_1_2:
          level_menu_label: APT-C31PVKCF
          level_menu_link: javascript:void(0);
      level_menu_1_3:
          level_menu_label: NSA-GENA3VXE
          level_menu_link: javascript:void(0);
  level_menu_2:
      level_menu_label: Projects
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_2_1:
          level_menu_label: We Cion
          level_menu_link: javascript:void(0);
      level_menu_2_2:
          level_menu_label: We Block
          level_menu_link: javascript:void(0);
      level_menu_2_3:
          level_menu_label: We Workload
          level_menu_link: javascript:void(0);
  level_menu_3:
      level_menu_label: Channel
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_3_1:
          level_menu_label: New Biz
          level_menu_link: javascript:void(0);
      level_menu_3_2:
          level_menu_label: New Tech
          level_menu_link: javascript:void(0);
      level_menu_3_3:
          level_menu_label: New Energy
          level_menu_link: javascript:void(0);

- # Level 4 Menu => Subset (1 -> 1.1 ~ 1.2) & Subset (2 -> 2.1 ~ 2.2) & Subset (3 -> 3.1 ~ 3.2)
  router_api_id: enterprise
  label_api: Enterprise
  link_api: #
  role_api: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
  level_menu_1:
      level_menu_label: Products
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_1_1:
          level_menu_label: Enterprise Basic
          level_menu_link: javascript:void(0);
      level_menu_1_2:
          level_menu_label: Enterprise Security
          level_menu_link: javascript:void(0);
      level_menu_1_3:
          level_menu_label: Enterprise Application
          level_menu_link: javascript:void(0);
  level_menu_2:
      level_menu_label: Solutions
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_2_1:
          level_menu_label: Universal Solution
          level_menu_link: javascript:void(0);
      level_menu_2_2:
          level_menu_label: Industry Solution
          level_menu_link: javascript:void(0);
      level_menu_2_3:
          level_menu_label: Other Solution
          level_menu_link: javascript:void(0);
  level_menu_3:
      level_menu_label: Scenarios
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_3_1:
          level_menu_label: Covid-19
          level_menu_link: /Covid-19
      level_menu_3_2:
          level_menu_label: Blockchain
          level_menu_link: javascript:void(0);
      level_menu_3_3:
          level_menu_label: Sustainability
          level_menu_link: javascript:void(0);
- # Level 5 Menu => Subset (1 -> 1.1 ~ 1.2) & Subset (2 -> 2.1 ~ 2.2) & Subset (3 -> 3.1 ~ 3.2)
  router_api_id: marketplace
  label_api: Marketplace
  link_api: #
  role_api: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
  level_menu_1:
      level_menu_label: Service
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_1_1:
          level_menu_label: Finance
          level_menu_link: javascript:void(0);
      level_menu_1_2:
          level_menu_label: Business
          level_menu_link: javascript:void(0);
      level_menu_1_3:
          level_menu_label: Juridical
          level_menu_link: javascript:void(0);
  level_menu_2:
      level_menu_label: Resources
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_2_1:
          level_menu_label: API Hub
          level_menu_link: javascript:void(0);
      level_menu_2_2:
          level_menu_label: Wiki Hub
          level_menu_link: javascript:void(0);
      level_menu_2_3:
          level_menu_label: Library Hub
          level_menu_link: javascript:void(0);
  level_menu_3:
      level_menu_label: Metaverse Club
      level_menu_link: #
      level_menu_role: 'role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'
      level_menu_3_1:
          level_menu_label: Stock Club
          level_menu_link: javascript:void(0);
      level_menu_3_2:
          level_menu_label: PE Fund Club
          level_menu_link: javascript:void(0);
      level_menu_3_3:
          level_menu_label: Open Source Club
          level_menu_link: javascript:void(0);

options_router_i18n_USA:
-
  options_label_api: About Us
  options_link_api: javascript:void(0);
-
  options_label_api: Company Culture
  options_link_api: javascript:void(0);
-
  options_label_api: Mission & Vision
  options_link_api: javascript:void(0);
-
  options_label_api: Privacy Policy
  options_link_api: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/Actions=InvokeRequest/TokenKeyPairs=Authorization/PublicizedAPI/Services/About/PrivacyPolicy/Intl/USA
-
  options_label_api: Help Center
  options_link_api: javascript:void(0);

footer_router_i18n_USA_v1:
- menu_title: "Industry Park"
-
  menu_items:
    open_label: "New Energy"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Tech Incubator"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Aerospace Tech"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "FIN Venture Capital"
    open_link: "javascript:void(0);"

footer_router_i18n_USA_v2:
- menu_title: "Discovery"
-
  menu_items:
    open_label: "Web 3.0"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Open NFTs"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Advanced Tech"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Decentralization"
    open_link: "javascript:void(0);"
-
  menu_items_v2:
    open_label: "Digital Economy"
    open_link: "javascript:void(0);"
-
  menu_items_v2:
    open_label: "Internet of Things"
    open_link: "javascript:void(0);"
-
  menu_items_v2:
    open_label: "New Infrastructure"
    open_link: "javascript:void(0);"
-
  menu_items_v2:
    open_label: "Artificial Intelligence"
    open_link: "javascript:void(0);"

footer_router_i18n_USA_v3:
- menu_title: "Enterprise"
-
  menu_items:
    open_label: "ANON TOKEN"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "ANON OKRs-E"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Workload Center"
    open_link: "javascript:void(0);"
-
  menu_items:
    open_label: "Crypto Exchange Hub"
    open_link: "javascript:void(0);"

#  ────────────────────────(END AUTOMATED BUILD SERVICE)──────────────────────────────────