# Basic Configuration
encoding: UTF-8
locale: en-US
title: "XXXXX"
keyword: "XXXXX"
email: XXXXX
organization: "XXXXX"
description: >-
  WE ARE ANON SYS. WE ARE LEGION.
baseurl: ""
url: ""
favicon: "XXXXX"

# Build settings
# theme: minima
plugins:
  - jekyll-feed


##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##

#  ────────────────────────(START AUTOMATED BUILD SERVICE)─────────────────────────────────

# PaaS Containers EASW Route Controller
api_vm_base_com: ANON SYS, INC.
api_vm_base_des: WE ARE ANON SYS. WE ARE LEGION.
api_base_network_route: /api/serverless/easw
api_base_static_route: /api/serverless/easw/includes/assets/
api_base_res_route: /api/serverless/easw/includes/assets/res/

#  ────────────────────────(END AUTOMATED BUILD SERVICE)──────────────────────────────────